dist: trusty
osx_image: xcode8.2
sudo: false
language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 3.3
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: nightly
    - os: osx
      python: nightly

script:
  - qmake -makefile NifSkope.pro

notifications:
    email: false
