dist: trusty
osx_image: xcode8.2
sudo: required
language: cpp
os:
  - linux
#  - osx
addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt551-trusty'
      - ubuntu-toolchain-r-test
    packages: [
      # static analysis
      clang-3.6,
      # qt5 requirement
      qt55-meta-minimal
    ]
matrix:
  fast_finish: true

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh'); source $QT_ENV_SCRIPT; fi

script:
  - qmake --version
  - qmake -makefile NifSkope.pro
  - make -j4

notifications:
    email: false
